#!/bin/bash
#author zhangge
#email zhgeaits@gmail.com
#description:
#	This is a shell to new a shell script file.

DATE=`date '+%Y-%m-%d %T'`
AUTHOR="zhangge"
EMAIL="zhgeaits@gmail.com"
DESC="description:愿我的家人和读者及读者的家人全体身体健康，一生平安！"

if [ $# -lt 1 ]
then
	echo "Usage:newcfile filename description"
	exit
fi

filename=$1
description=" "

if [ "$2" != '' ];then
    description=$2
fi

user=`whoami`
touch $filename
chown $user $filename
chgrp $user $filename

echo "/*date:   $DATE" >> $filename
echo " *author: $AUTHOR" >> $filename
echo " *email:  $EMAIL" >> $filename
echo " *$DESC" >> $filename
echo -e " *$description" >> $filename
echo " */" >> $filename

vim $filename
